apiVersion: skaffold/v2beta17 latest
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./Infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ranga/authservice          # image name that we prefer
      context: Authservice              # Folder that contains the source files
      docker: 
        dockerfile: Dockerfile
      sync:                             # Sync is the watcher for the file changes.
        manual:
          - src: 'src/**/*.cs'
            dest: .
            