apiVersion: skaffold/v2beta17
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./Infrastructure/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: ranga/authservice          # image name that we prefer
      context: AuthService              # Folder that contains the source files
      docker: 
        dockerfile: Dockerfile
      sync:                             # Sync is the watcher for the file changes.
        manual:
        - src: '**.cs'                   # watching for Any .cs file changes
          dest: .                       # destination where the files needs to be copied in the running container. 
            