apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopservice
  template:
    metadata:
      labels:
        app: shopservice
    spec:
      containers:
        - name: shopservice
          image: shoppinglist/shopservice:0.0.1       
