apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopservice
  template:
    metadata:
      labels:
        app: shopservice
    spec:
      containers:
        - name: shopservice
          image: ranga/shopservice:latest
---
apiVersion: v1
kind: Service
metadata:
  name: shopservice-clusterip-srv
spec:
  selector:
    app: shopservice
  ports:
    - name: shopservice
      protocol: TCP
      port: 5002
      targetPort: 5002        